BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Controllers/SlideController.cs
using BaselFinalProjectApp.Areas.Admin.Models.ViewModel;
using BaselFinalProjectApp.Data;
using BaselFinalProjectApp.Models.PageModel.HomePageModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BaselFinalProjectApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SlideController : Controller
    {

        private BaselDbContext _baselDb { get; set; }

        public SlideController(BaselDbContext baselDb)
        {
            _baselDb = baselDb;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<SlideLanguage> slideLanguages = _baselDb.Slides
                .SelectMany(a => a.SlideLanguages
                    .Where(x => x.LanguageId == 1))
                        .Include(x => x.Slide)
                            .ToList();

            return View(slideLanguages);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            try
            {
                if (id!=null)
                {
                     List<SlideLanguage> slideLanguages = _baselDb.Slides
                        .SelectMany(x => x.SlideLanguages
                           .Where(z => z.Slide.Id == id))
                               .Include(a => a.Slide)
                                   .ToList();

                    SlideModelEdit slideModelEdit = new SlideModelEdit()
                    {
                        Id = slideLanguages.Select(x => x.SlideId).FirstOrDefault(),

                        EngHeader = slideLanguages.Where(x => x.LanguageId == 1).Select(x => x.Header).SingleOrDefault(),
                        AzHeader = slideLanguages.Where(x => x.LanguageId == 2).Select(x => x.Header).SingleOrDefault(),
                        RuHeader = slideLanguages.Where(x => x.LanguageId == 3).Select(x => x.Header).SingleOrDefault(),

                        EngTitle = slideLanguages.Where(x => x.LanguageId == 1).Select(x => x.Title).SingleOrDefault(),
                        AzTitle = slideLanguages.Where(x => x.LanguageId == 2).Select(x => x.Title).SingleOrDefault(),
                        RuTitle = slideLanguages.Where(x => x.LanguageId == 3).Select(x => x.Title).SingleOrDefault(),

                        EngDescription = slideLanguages.Where(x => x.LanguageId == 1).Select(x => x.Description).SingleOrDefault(),
                        AzDescription = slideLanguages.Where(x => x.LanguageId == 2).Select(x => x.Description).SingleOrDefault(),
                        RuDescription = slideLanguages.Where(x => x.LanguageId == 3).Select(x => x.Description).SingleOrDefault(),

                        EngFooter = slideLanguages.Where(x => x.LanguageId == 1).Select(x => x.Footer).SingleOrDefault(),
                        AzFooter = slideLanguages.Where(x => x.LanguageId == 2).Select(x => x.Footer).SingleOrDefault(),
                        RuFooter = slideLanguages.Where(x => x.LanguageId == 3).Select(x => x.Footer).SingleOrDefault(),

                        OldImage = slideLanguages.Select(x => x.Slide).Select(z => z.Image).FirstOrDefault()
                    };
                    return View(slideModelEdit);
                }
            }
            catch (Exception exp)
            {
                return View(exp.Message);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SlideModelEdit slideModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (slideModel?.Id != null)
                    {
                        List<SlideLanguage> slideLanguages = _baselDb.Slides
                            .SelectMany(x => x.SlideLanguages
                               .Where(z => z.Slide.Id == slideModel.Id))
                                   .Include(a => a.Slide)
                                       .ToList();

                        foreach (SlideLanguage item in slideLanguages)
                        {
                            if (item.LanguageId == 1)
                            {
                                item.Header = slideModel.EngHeader;
                                item.Title = slideModel.EngTitle;
                                item.Description = slideModel.EngDescription;
                                item.Footer = slideModel.EngFooter;
                            }
                            else if (item.LanguageId == 2)
                            {
                                item.Header = slideModel.AzHeader;
                                item.Title = slideModel.AzTitle;
                                item.Description = slideModel.AzDescription;
                                item.Footer = slideModel.AzFooter;
                            }
                            else if (item.LanguageId == 3)
                            {
                                item.Header = slideModel.RuHeader;
                                item.Title = slideModel.RuTitle;
                                item.Description = slideModel.RuDescription;
                                item.Footer = slideModel.RuFooter;
                            }
                        }

                        Slide slide = slideLanguages.Select(x => x.Slide).FirstOrDefault();

                        string imageName = slideModel.Image == null ? slideModel.OldImage : slideModel.Image.FileName;

                        if (imageName!=null)
                        {
                            if (slide.Image != imageName)
                            {
                                if (slideModel.Image.ContentType.Contains("image/"))
                                {
                                    string ImageName = string.Empty;

                                    string fileLocationDelete = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\lib\\image", slide.Image);

                                    if (System.IO.File.Exists(fileLocationDelete))
                                    {
                                        System.IO.File.Delete(fileLocationDelete);

                                        ImageName = DateTime.Now.ToString("yyyyMMddHHmmssss") + slideModel.Image.FileName;

                                        string fileLocationAdd = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\lib\\image", ImageName);

                                        using (FileStream fileStream = new FileStream(fileLocationAdd, FileMode.Create))
                                        {
                                            await slideModel.Image.CopyToAsync(fileStream);
                                        }

                                        slide.Image = ImageName;

                                        _baselDb.Slides.Update(slide);

                                        await _baselDb.SaveChangesAsync();

                                        return RedirectToAction("Index");
                                    }
                                    else
                                        ModelState.AddModelError("", "File is not exists");
                                }
                                else
                                    ModelState.AddModelError("", "You can upload only image");
                            }
                            await _baselDb.SaveChangesAsync();
                            return RedirectToAction("Index");
                        }
                        else
                            ModelState.AddModelError("", "Image is not found");
                    }
                }
            }
            catch (Exception exp)
            {
                return View(exp.Message);
            }
            return RedirectToAction("Edit");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            try
            {
                List<SlideLanguage> slideLanguages = _baselDb.Slides
                   .SelectMany(x => x.SlideLanguages
                           .Where(z => z.Slide.Id == id))
                               .Include(a => a.Slide)
                                   .ToList();

                return View(slideLanguages);
            }
            catch (Exception exp)
            {
                return View(exp.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, string name)
        {
            string fileName = string.Empty;

            try
            {
                List<SlideLanguage> slideLanguages = _baselDb.Slides
                   .SelectMany(x => x.SlideLanguages
                           .Where(z => z.Slide.Id == id))
                               .Include(a => a.Slide)
                                   .ToList();

                _baselDb.Slides
                   .Select(x => x.SlideLanguages
                        .Remove(slideLanguages
                            .Find(z => z.LanguageId == 1)));

                _baselDb.Slides
                   .Select(x => x.SlideLanguages
                        .Remove(slideLanguages
                            .Find(z => z.LanguageId == 2)));

                _baselDb.Slides
                   .Select(x => x.SlideLanguages
                        .Remove(slideLanguages
                            .Find(z => z.LanguageId == 3)));


                _baselDb.Slides
                    .Remove(slideLanguages
                        .Where(x => x.Slide.Id == id)
                            .Select(x => x.Slide)
                                .FirstOrDefault());

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Slide/Create.cshtml
@model BaselFinalProjectApp.Areas.Admin.Models.ViewModel.SlideModelCreate

<section class="p-3">
    <form asp-action="Create" asp-controller="Slide" method="post" enctype="multipart/form-data" style="width:50%; margin:0px auto;">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="EngHeader"></label>
            <input asp-for="EngHeader" type="text" class="form-control">
            <span asp-validation-for="EngHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzHeader"></label>
            <input asp-for="AzHeader" type="text" class="form-control">
            <span asp-validation-for="AzHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuHeader"></label>
            <input asp-for="RuHeader" type="text" class="form-control">
            <span asp-validation-for="RuHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngTitle"></label>
            <input asp-for="EngTitle" type="text" class="form-control">
            <span asp-validation-for="EngTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzTitle"></label>
            <input asp-for="AzTitle" type="text" class="form-control">
            <span asp-validation-for="AzTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuTitle"></label>
            <input asp-for="RuTitle" type="text" class="form-control">
            <span asp-validation-for="RuTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngDescription"></label>
            <input asp-for="EngDescription" type="text" class="form-control">
            <span asp-validation-for="EngDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzDescription"></label>
            <input asp-for="AzDescription" type="text" class="form-control">
            <span asp-validation-for="AzDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuDescription"></label>
            <input asp-for="RuDescription" type="text" class="form-control">
            <span asp-validation-for="RuDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngFooter"></label>
            <input asp-for="EngFooter" type="text" class="form-control">
            <span asp-validation-for="EngFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzFooter"></label>
            <input asp-for="AzFooter" type="text" class="form-control">
            <span asp-validation-for="AzFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuFooter"></label>
            <input asp-for="RuFooter" type="text" class="form-control">
            <span asp-validation-for="RuFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" accept="image/*" type="file" class="form-control form-control-line">
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <button type="submit" class="btn w-100 btn-dark">Create</button>
        <a asp-controller="Slide" asp-action="Index" class="text-success w-100 btn btn-dark mt-2 mb-3">Back List</a>
    </form>
</section>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Slide/Delete.cshtml
@using BaselFinalProjectApp.Models.PageModel.HomePageModel
@model List<SlideLanguage>

<table class="table table-dark">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Header</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Footer</th>
            <th scope="col">Image</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Where(x => x.LanguageId == 1).Select(x => x.Header).SingleOrDefault()</td>
            <td>@Model.Where(x => x.LanguageId == 1).Select(x => x.Title).SingleOrDefault()</td>
            <td>@Model.Where(x => x.LanguageId == 1).Select(x => x.Description).SingleOrDefault()</td>
            <td>@Model.Where(x => x.LanguageId == 1).Select(x => x.Footer).SingleOrDefault()</td>
            <td>
                <img width="80" height="100" src="~/lib/image/@Model.Select(z => z.Slide.Image).FirstOrDefault()" />
            </td>
        </tr>
    </tbody>
</table>
<form asp-controller="Slide" asp-action="Delete" method="post">
    <input type="hidden" value="@Model.Select(z => z.Slide.Id).FirstOrDefault()" />
    <button type="submit" class="btn w-50 btn-dark ml-5 mb-3">Delete</button>
</form>
<a asp-controller="Slide" asp-action="Index" class="text-success w-50 btn btn-dark ml-5 mb-3">Back List</a>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Slide/Edit.cshtml
@model BaselFinalProjectApp.Areas.Admin.Models.ViewModel.SlideModelEdit
@using BaselFinalProjectApp.Models.PageModel.AccountPageModel
@using BaselFinalProjectApp.Areas.Admin.Models.ViewModel


<section class="p-3">
    <form asp-action="Edit" asp-controller="Slide" method="post" enctype="multipart/form-data" style="width:50%; margin:0px auto;">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input asp-for="Id" type="hidden" value="@Model.Id" class="form-control">
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngHeader"></label>
            <input asp-for="EngHeader" type="text" value="@Model.EngHeader" class="form-control">
            <span asp-validation-for="EngHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzHeader"></label>
            <input asp-for="AzHeader" type="text" value="@Model.AzHeader" class="form-control">
            <span asp-validation-for="AzHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuHeader"></label>
            <input asp-for="RuHeader" value="@Model.RuHeader" type="text" class="form-control">
            <span asp-validation-for="RuHeader" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngTitle"></label>
            <input asp-for="EngTitle" type="text" value="@Model.EngTitle" class="form-control">
            <span asp-validation-for="EngTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzTitle"></label>
            <input asp-for="AzTitle" type="text" value="@Model.AzTitle" class="form-control">
            <span asp-validation-for="AzTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuTitle"></label>
            <input asp-for="RuTitle" type="text" value="@Model.RuTitle" class="form-control">
            <span asp-validation-for="RuTitle" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngDescription"></label>
            <input asp-for="EngDescription" type="text" value="@Model.EngDescription" class="form-control">
            <span asp-validation-for="EngDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzDescription"></label>
            <input asp-for="AzDescription" type="text" value="@Model.AzDescription" class="form-control">
            <span asp-validation-for="AzDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuDescription"></label>
            <input asp-for="RuDescription" value="@Model.RuDescription" type="text" class="form-control">
            <span asp-validation-for="RuDescription" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EngFooter"></label>
            <input asp-for="EngFooter" type="text" class="form-control">
            <span asp-validation-for="EngFooter" value="@Model.EngFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzFooter"></label>
            <input asp-for="AzFooter" value="@Model.AzFooter" type="text" class="form-control">
            <span asp-validation-for="AzFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuFooter"></label>
            <input asp-for="RuFooter" value="@Model.RuFooter" type="text" class="form-control">
            <span asp-validation-for="RuFooter" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" accept="image/*" type="file" class="form-control form-control-line">
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div>
            <img src="~/lib/image/@Model.OldImage" width="100"/>
        </div>
        <div class="form-group">
            <input asp-for="OldImage" type="hidden" value="@Model.OldImage" class="form-control">
            <span asp-validation-for="OldImage" class="text-danger"></span>
        </div>
        <button type="submit" class="btn w-100 btn-dark">Update</button>
        <a asp-controller="Slide" asp-action="Index" class="text-success w-100 btn btn-dark mt-2 mb-3">Back List</a>
    </form>
</section>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Slide/Index.cshtml
@model IEnumerable<BaselFinalProjectApp.Models.PageModel.HomePageModel.SlideLanguage>

<section class="mb-4">
    <div class="p-3 bg-secondary text-white" style="font-size:1.5rem; text-align:center;">Slide</div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Header</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Footer</th>
                <th scope="col">Image</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (SlideLanguage item in Model)
            {
                <tr>
                    <th>@item.Header</th>
                    <td>@item.Title</td>
                    <td>@item.Description</td>
                    <td>@item.Footer</td>
                    <td>
                        <img width="70" height="90" src="~/lib/image/@item.Slide.Image" />
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Slide" asp-route-id="@item.Slide.Id">Edit</a>
                    </td>
                    <td>
                        <a asp-action="Delete" asp-controller="Slide" asp-route-id="@item.Slide.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-action="Create" asp-controller="Slide" class="btn btn-secondary btn-lg btn-block">Create</a>
</section>