BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BaselFinalProjectApp.Areas.Admin.Models.ViewModel;
using BaselFinalProjectApp.Data;
using BaselFinalProjectApp.Models.MainModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BaselFinalProjectApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ColorController : Controller
    {
        private BaselDbContext _baselDb { get; set; }

        public ColorController(BaselDbContext baselDb)
        {
            _baselDb = baselDb;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<ColorLanguage> colorLanguages = _baselDb.Colors
                .SelectMany(x=>x.ColorLanguages)
                    .Where(x=>x.LanguageId==1)
                        .Include(x=>x.Color)
                            .ToList();

            return View(colorLanguages);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ColorsModel ColorsModel)
        {
            if (ModelState.IsValid)
            {
                List<ColorLanguage> colorLanguages = new List<ColorLanguage>()
                {
                    new ColorLanguage()
                    {
                        LanguageId=1,
                        Name = ColorsModel.EngName
                    },
                    new ColorLanguage()
                    {
                        LanguageId=2,
                        Name = ColorsModel.AzName
                    },
                    new ColorLanguage()
                    {
                        LanguageId=3,
                        Name = ColorsModel.RuName
                    }
                };

                Color category = new Color()
                {
                    ColorCode = ColorsModel.ColorCode,
                    ColorLanguages = colorLanguages
                };

                await _baselDb.Colors.AddAsync(category);

                await _baselDb.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            ColorLanguage colorLanguage = _baselDb.Colors
                .SelectMany(x => x.ColorLanguages)
                    .Where(x => x.LanguageId == 1)
                        .Include(x => x.Color)
                            .Where(x => x.ColorId == id)
                                .SingleOrDefault();

            return View(colorLanguage);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id,string name)
        {
            if (id != null)
            {
                _baselDb.Colors.Remove(await _baselDb.Colors.FindAsync(id));

                _baselDb.Colors.Select(x => x.ColorLanguages
                    .Remove(_baselDb.Colors.Where(a => a.Id == id)
                        .SelectMany(z => z.ColorLanguages).SingleOrDefault()));

                 await _baselDb.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            List<ColorLanguage> colorLanguages = _baselDb.Colors
                .SelectMany(x => x.ColorLanguages)
                        .Include(x => x.Color)
                            .Where(x => x.ColorId == id)
                                .ToList();

            ColorData colorData = new ColorData()
            {
                ColorLanguages = colorLanguages,
                ColorsModel = new ColorsModel()
            };

            return View(colorData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ColorsModel colorsModel)
        {
            if (ModelState.IsValid)
            {
                List<ColorLanguage> colorLanguages = _baselDb.Colors
                    .SelectMany(x => x.ColorLanguages)
                        .Include(x => x.Color)
                            .Where(x => x.ColorId == colorsModel.Id)
                                .ToList();

                foreach (ColorLanguage item in colorLanguages)
                {
                    if (item.LanguageId == 1)
                    {
                        item.Name = colorsModel.EngName;
                    }
                    if (item.LanguageId == 2)
                    {
                        item.Name = colorsModel.AzName;
                    }
                    if (item.LanguageId == 3)
                    {
                        item.Name = colorsModel.RuName;
                    }
                }

                Color color = _baselDb.Colors.FindAsync(colorsModel.Id).Result;

                color.ColorCode = colorsModel.ColorCode;

                await _baselDb.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Edit");
        }
    }
}

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Color/Create.cshtml
@model BaselFinalProjectApp.Areas.Admin.Models.ViewModel.ColorsModel
@using BaselFinalProjectApp.Areas.Admin.Models.ViewModel


<section class="p-3">
    <form asp-action="Create" asp-controller="Color" method="post" style="width:50%; margin:0px auto;">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="EngName"></label>
            <input asp-for="EngName" type="text" class="form-control">
            <span asp-validation-for="EngName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="AzName"></label>
            <input asp-for="AzName" type="text" class="form-control">
            <span asp-validation-for="AzName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RuName"></label>
            <input asp-for="RuName" type="text" class="form-control">
            <span asp-validation-for="RuName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ColorCode"></label>
            <input asp-for="ColorCode" type="text" class="form-control">
            <span asp-validation-for="ColorCode" class="text-danger"></span>
        </div>
        <button type="submit" class="btn w-100 btn-dark">Create</button>
        <a asp-controller="Color" asp-action="Index" class="text-success w-100 btn btn-dark mt-2 mb-3">Back List</a>
    </form>
</section>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Color/Delete.cshtml
@using BaselFinalProjectApp.Models.MainModel
@model ColorLanguage

<table class="table table-dark">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">ColorCode</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Name</td>
            <td>@Model.Color.ColorCode</td>
        </tr>
    </tbody>
</table>
<form asp-controller="Color" asp-action="Delete" method="post">
    <input type="hidden" value="@Model.Color.Id" />
    <button type="submit" class="btn w-50 btn-dark ml-5 mb-3">Delete</button>
</form>
<a asp-controller="Color" asp-action="Index" class="text-success w-50 btn btn-dark ml-5 mb-3">Back List</a>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Color/Edit.cshtml
@model BaselFinalProjectApp.Areas.Admin.Models.ViewModel.ColorData


<section class="p-3">
    <form asp-action="Edit" asp-controller="Color" method="post" style="width:50%; margin:0px auto;">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input asp-for="ColorsModel.Id" value="@Model.ColorLanguages.Where(x=>x.LanguageId==1).Select(x=>x.ColorId).SingleOrDefault()" type="hidden" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="ColorsModel.EngName"></label>
            <input asp-for="ColorsModel.EngName" value="@Model.ColorLanguages.Where(x=>x.LanguageId==1).Select(x=>x.Name).SingleOrDefault()" type="text" class="form-control">
            <span asp-validation-for="ColorsModel.EngName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ColorsModel.AzName"></label>
            <input asp-for="ColorsModel.AzName" value="@Model.ColorLanguages.Where(x=>x.LanguageId==2).Select(x=>x.Name).SingleOrDefault()" type="text" class="form-control">
            <span asp-validation-for="ColorsModel.AzName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ColorsModel.RuName"></label>
            <input asp-for="ColorsModel.RuName" value="@Model.ColorLanguages.Where(x=>x.LanguageId==3).Select(x=>x.Name).SingleOrDefault()" type="text" class="form-control">
            <span asp-validation-for="ColorsModel.RuName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ColorsModel.ColorCode"></label>
            <input asp-for="ColorsModel.ColorCode" value="@Model.ColorLanguages.Where(x=>x.LanguageId==1).Select(x=>x.Color).Select(x=>x.ColorCode).FirstOrDefault()" type="text" class="form-control">
            <span asp-validation-for="ColorsModel.ColorCode" class="text-danger"></span>
        </div>
        <button type="submit" class="btn w-100 btn-dark">Update</button>
        <a asp-controller="Color" asp-action="Index" class="text-success w-100 btn btn-dark mt-2 mb-3">Back List</a>
    </form>
</section>

BaselApp(ASP Core MVC)/BaselProjectApp (main)/BaselFinalProjectApp/Areas/Admin/Views/Color/Index.cshtml
@model List<BaselFinalProjectApp.Models.MainModel.ColorLanguage>
@using BaselFinalProjectApp.Models.MainModel

<section class="mb-4">
    <div class="p-3 bg-secondary text-white" style="font-size:1.5rem; text-align:center;">Color</div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">ColorCode</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (ColorLanguage item in Model)
            {
            <tr>
                <th>@item.Name</th>
                <td>@item.Color.ColorCode</td>
                <td>
                    <a asp-action="Edit" asp-controller="Color" asp-route-id="@item.Color.Id">Edit</a>
                </td>
                <td>
                    <a asp-action="Delete" asp-controller="Color" asp-route-id="@item.Color.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <a asp-action="Create" asp-controller="Color" class="btn btn-secondary btn-lg btn-block">Create</a>
</section>